language: c

notifications:
  email: false

before_script:
# travis has changed to 64-bit and we require 32-bit compatibility libraries
  - wget -c http://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2012.09-63-arm-none-eabi-i686-pc-linux-gnu.tar.bz2
  - tar jxvf arm-2012.09-63-arm-none-eabi-i686-pc-linux-gnu.tar.bz2
  - sudo apt-get update
  - "sudo apt-get -qq install libc6:i386 libgcc1:i386 libstdc++5:i386 libstdc++6:i386 || true"
  - git clone --depth 1 https://github.com/RT-Thread/rt-thread.git
  - export RTT_ROOT=`pwd`"/rt-thread"
  - export RTT_CC='gcc'
  - export RTT_EXEC_PATH=`pwd`"/arm-2012.09/bin"

script:
  - ./Software/examples/buildbot.py
